feat: dockefile for ncr and publish on ghcr
ForkbombEu/DIDroom_microservices pull request #6
Opened 2023-12-11 13:27 UTC by albertolerda

2023-12-11 15:59 UTC, puria requested changes

2023-12-11 15:59 UTC, puria commented on README.md
> +docker pull ghcr.io/albertolerda/didroom_microservices:latest
fix the address

2023-12-11 15:59 UTC, puria commented on credential_issuer/health.keys.json
> +    "timestamp_srv": "http://apiroom.net:3312"
ahaha this is not reliable at all ;p do a query on the server itself, a localhost... so you check that is tautologically doing a self-assesment plz!

2023-12-11 15:59 UTC, puria commented on credential_issuer/health.schema.json
The schema also is relaly not needed, I guess no-intended use via GUI...

2023-12-11 19:32 UTC, albertolerda commented on credential_issuer/health.schema.json
without the schema, the service didn't start...

2023-12-12 09:40 UTC, puria approved these changes

2023-12-12 09:41 UTC, puria approved these changes

2023-12-12 09:42 UTC, merged